Carro/urls.py
from django.urls import path
from . import views

app_name = "carro"

urlpatterns = [
    path('agregar/<int:producto_id>/', views.agregar_producto, name="agregar"),
    path('eliminar/<int:producto_id>', views.eliminar_producto, name="eliminar"),
    path('restar/<int:producto_id>', views.restar_producto, name="restar"),
    path('limpiar/', views.limpiar_carrito, name="limpiar"),
]

ProyectoWeb/urls.py
from django.contrib import admin
from django.urls import path, include
 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('servicios/', include('Servicios.urls')),
    path('contacto/', include('Contacto.urls')),
    path('tienda/', include('Tienda.urls')),
    path('carro/', include('Carro.urls')),
    path('autenticacion/', include('Autenticacion.urls')),
    path('procesar_pedidos/', include('Pedidos.urls')),
    path('', include('ProyectoWebApp.urls')),
]

Tienda/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.tienda, name="Tienda"),
    path('categoria/<int:categoria_id>', views.productos_filtrados, name="categoria"),
]

Carro/models.py
from django.db import models

# Create your models here.

Tienda/models.py
from django.db import models

# Create your models here.

class CategoriaProd(models.Model):
    nombre = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "categoriaProd"
        verbose_name_plural = "categoriasProd"

    def __str__(self):
        return self.nombre
    
class Producto(models.Model):
    nombre = models.CharField(max_length=50)
    categorias = models.ForeignKey(CategoriaProd, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="tienda", null=True, blank=True)
    precio = models.FloatField()
    disponibilidad = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name = "Producto"
        verbose_name_plural = "Productos"

    def __str__(self):
        return self.nombre

Carro/views.py
from django.shortcuts import render, redirect
from .carro import Carro
from Tienda.models import Producto

# Create your views here.

def agregar_producto(request, producto_id):
    carrito = Carro(request)
    producto = Producto.objects.get(id=producto_id)
    carrito.agregar(producto)
    return redirect("Tienda")

def eliminar_producto(request, producto_id):
    carrito = Carro(request)
    producto = Producto.objects.get(id=producto_id)
    carrito.eliminar(producto)
    return redirect("Tienda")

def restar_producto(request, producto_id):
    carrito = Carro(request)
    producto = Producto.objects.get(id=producto_id)
    carrito.restar_producto(producto)
    return redirect("Tienda")

def limpiar_carrito(request):
    carrito = Carro(request)
    carrito.limpiar_carro()
    return redirect("Tienda")

Tienda/views.py
from django.shortcuts import render
from .models import Producto, CategoriaProd

# Create your views here.

def tienda(request):
    productos = Producto.objects.all()
    categorias = CategoriaProd.objects.all()
    return render(request, "tienda/tienda.html", {"productos": productos, "categorias": categorias})

def productos_filtrados(request, categoria_id):
    categorias = CategoriaProd.objects.all()
    categoria_seleccionada = CategoriaProd.objects.get(id=categoria_id)
    productos_filtrados = Producto.objects.filter(categorias=categoria_seleccionada)
    return render(request, "tienda/categoria.html", {"productos_filtrados": productos_filtrados, "categorias": categorias})

Tienda/templates/carro/widget.html
{% load static %}

<table class="table table-bordered mt-2 carrito">
    <thead>
        <tr>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Total</th>
            <th>Modificar</th>
        </tr>
    </thead>
    <tbody>
        {% if request.session.carro.items %}
            {% for key, value in request.session.carro.items %}
                <tr class="text-center">
                    <td>{{ value.nombre }}</td>
                    <td>{{ value.cantidad }}</td>
                    <td>${{ value.precio }}</td>
                    <td>
                        <a href="{% url 'carro:agregar' value.producto_id%}" class="btn btn-sm btn-success">+</a>
                        <a href="{% url 'carro:restar' value.producto_id%}" class="btn btn-sm btn-danger">-</a>
                    </td>
                </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="4">
                    <div class="alert alert-danger text-center">
                        Sin productos en el carrito
                    </div>
                </td>
            </tr>
        {% endif %}
    </tbody>
    <tfoot>
        <tr>
            <td colspan="4">Total Compra: ${{ importe_total_carro }}</td>
        </tr>
        {% if request.session.carro.items %}
        <tr>
            <td colspan="4" style="text-align: center;">
                <a href="{% url 'procesar_pedido' %}" class="btn btn-success">Comprar</a>
            </td>
        </tr>
        {% endif %}
    </tfoot>
</table>